name: Makefile CI

on:
  push:
    branches: [ "ofox-12.1" ]
  pull_request:
    branches: [ "ofox-12.1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: . build/envsetup.sh

    - name: Install dependencies
      run: lunch twrp_a10-eng

    - name: Run check
      run: make recoveryimage -j$(nproc --all)
